//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeiXinMvcWeb.Models.WeiXinDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nav_Item
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public int New_Flag { get; set; }
        public int New_Seq { get; set; }
        public int Nav_ItemsID { get; set; }
    
        public virtual Nav_Items Nav_Items { get; set; }
    }
}
