//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeiXinMvcWeb.Models.WeiXinDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wb_Info
    {
        public int Wb_ID { get; set; }
        public string Src { get; set; }
        public int Verify_Flag { get; set; }
        public string Verify_Info { get; set; }
        public string Nick_Name { get; set; }
        public string Head_Img_Url { get; set; }
        public string Verify_Code { get; set; }
        public int Manual_Review { get; set; }
        public int Can_Sync { get; set; }
        public int Verify_Status { get; set; }
        public int User_InfoUserID { get; set; }
    
        public virtual User_Info User_Info { get; set; }
    }
}
