//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeiXinMvcWeb.Models.WeiXinDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeiXinEntities : DbContext
    {
        public WeiXinEntities()
            : base("name=WeiXinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Test> Test { get; set; }
        public DbSet<Nav_Item> Nav_Item { get; set; }
        public DbSet<Nav_Items> Nav_Items { get; set; }
        public DbSet<Base_Resp> Base_Resp { get; set; }
    }
}
